#!/usr/bin/env python3
"""
Embeds firmware/data/ web files into firmware/web_content.h.
Run this after editing index.html, style.css, or app.js:

    python tools/web_to_header.py
"""
import os

ROOT  = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA  = os.path.join(ROOT, "firmware", "data")
OUT   = os.path.join(ROOT, "firmware", "web_content.h")
DELIM = "TOKIWEB"

FILES = [
    ("WEB_HTML", "index.html"),
    ("WEB_CSS",  "style.css"),
    ("WEB_JS",   "app.js"),
]

MIME = {
    "WEB_HTML": "text/html; charset=utf-8",
    "WEB_CSS":  "text/css",
    "WEB_JS":   "application/javascript",
}

with open(OUT, "w", encoding="utf-8", newline="\n") as out:
    out.write("// Auto-generated by tools/web_to_header.py — do not edit by hand.\n")
    out.write("// Re-generate after changing firmware/data/ web files:\n")
    out.write("//   python tools/web_to_header.py\n")
    out.write("#pragma once\n\n")

    for name, filename in FILES:
        src = os.path.join(DATA, filename)
        with open(src, "r", encoding="utf-8") as f:
            content = f.read()
        out.write(f'static const char {name}[] = R"{DELIM}({content}){DELIM}";\n\n')

print(f"generated  {os.path.relpath(OUT)}")
