// Auto-generated by tools/web_to_header.py — do not edit by hand.
// Re-generate after changing firmware/data/ web files:
//   python tools/web_to_header.py
#pragma once

static const char WEB_HTML[] = R"TOKIWEB(<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>tokiboks</title>
<link rel="stylesheet" href="/style.css">
</head>
<body>
<header>
  <span class="logo">tokiboks</span>
  <span class="sub">configuration</span>
</header>
<main>
  <nav class="tabs">
    <button class="tab active" data-tab="creds">Credentials</button>
    <button class="tab" data-tab="srv">Music Player</button>
    <button class="tab" data-tab="map">Music Mapping</button>
  </nav>

  <section id="tab-creds" class="panel active">
    <form id="form-creds">
      <fieldset>
        <legend>WiFi</legend>
        <label><span>SSID</span><input type="text" name="wifi_ssid" autocomplete="off"></label>
        <label><span>Password</span><input type="password" name="wifi_password" autocomplete="new-password"></label>
      </fieldset>
      <fieldset>
        <legend>Admin</legend>
        <label><span>Username</span><input type="text" name="admin_username" autocomplete="off"></label>
        <label><span>Password</span><input type="password" name="admin_password" autocomplete="new-password"></label>
      </fieldset>
      <div class="row">
        <button class="btn" type="submit">Save</button>
        <button class="btn outline" type="button" id="btn-restart">Restart device</button>
      </div>
    </form>
  </section>

  <section id="tab-srv" class="panel">
    <form id="form-srv">
      <fieldset>
        <legend>Music player</legend>
        <label><span>Host / IP address</span><input type="text" name="server_host" autocomplete="off"></label>
        <label><span>Port</span><input type="number" name="server_port" min="1" max="65535"></label>
      </fieldset>
      <div class="row"><button class="btn" type="submit">Save</button></div>
    </form>
  </section>

  <section id="tab-map" class="panel">
    <div class="tb-hdr"><button id="btn-save-map" class="btn">Save</button></div>
    <div class="tbl-wrap">
      <table>
        <thead><tr>
          <th class="th-n">#</th>
          <th class="th-rfid">RFID</th>
          <th>What to play</th>
        </tr></thead>
        <tbody id="map-body"></tbody>
      </table>
    </div>
  </section>
</main>
<div id="toast"></div>
<script src="/app.js"></script>
</body>
</html>
)TOKIWEB";

static const char WEB_CSS[] = R"TOKIWEB(:root {
  --bg:   #f4f6f9;
  --sur:  #fff;
  --bdr:  #dde3ed;
  --hdr:  #1a1a2e;
  --pri:  #4a6cf7;
  --pri2: #3a57d4;
  --txt:  #1e2535;
  --mut:  #68748e;
  --hl:   #fffbeb;
  --hlb:  #f59e0b;
  --alt:  #f8fafc;
  --r:    6px;
  --f:    -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
  --fm:   'Cascadia Code', 'Consolas', monospace;
}

*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

body {
  font-family: var(--f);
  background: var(--bg);
  color: var(--txt);
  font-size: 14px;
  line-height: 1.6;
}

header {
  background: var(--hdr);
  color: #e8edf8;
  padding: .875rem 1.5rem;
  display: flex;
  align-items: baseline;
  gap: .6rem;
}
.logo { font-size: 1.125rem; font-weight: 700; letter-spacing: .04em; color: #fff; }
.sub  { font-size: .75rem; color: #9ba8c4; text-transform: uppercase; letter-spacing: .07em; }

main { max-width: 860px; margin: 2rem auto; padding: 0 1.25rem; }

.tabs {
  display: flex;
  border-bottom: 1px solid var(--bdr);
  margin-bottom: 2rem;
}
.tab {
  background: none;
  border: none;
  border-bottom: 2px solid transparent;
  margin-bottom: -1px;
  padding: .625rem 1.125rem;
  font: 500 .875rem var(--f);
  color: var(--mut);
  cursor: pointer;
  transition: color .15s, border-color .15s;
  outline: none;
}
.tab:hover  { color: var(--txt); }
.tab.active { color: var(--pri); border-bottom-color: var(--pri); }

.panel        { display: none; }
.panel.active { display: block; }

form { display: flex; flex-direction: column; gap: 1.5rem; }

fieldset {
  border: 1px solid var(--bdr);
  border-radius: var(--r);
  padding: 1.125rem 1.25rem 1.25rem;
  display: flex;
  flex-direction: column;
  gap: .875rem;
}
legend {
  padding: 0 .375rem;
  font: 600 .75rem var(--f);
  text-transform: uppercase;
  letter-spacing: .07em;
  color: var(--mut);
}

label { display: flex; flex-direction: column; gap: .3rem; }
label span { font: 500 .8125rem var(--f); }

input[type=text],
input[type=password],
input[type=number] {
  font: .875rem var(--f);
  padding: .5rem .75rem;
  border: 1px solid var(--bdr);
  border-radius: 4px;
  background: var(--sur);
  color: var(--txt);
  outline: none;
  width: 100%;
  max-width: 380px;
  transition: border-color .15s, box-shadow .15s;
}
input:focus {
  border-color: var(--pri);
  box-shadow: 0 0 0 3px rgba(74,108,247,.12);
}

.row { padding-top: .25rem; display: flex; gap: .75rem; align-items: center; }

.btn.outline {
  background: transparent;
  color: var(--pri);
  border: 1px solid var(--pri);
}
.btn.outline:hover { background: rgba(74,108,247,.08); }

.btn {
  font: 500 .875rem var(--f);
  padding: .5rem 1.25rem;
  background: var(--pri);
  color: #fff;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  transition: background .15s;
}
.btn:hover { background: var(--pri2); }

.tb-hdr {
  display: flex;
  justify-content: flex-end;
  margin-bottom: .875rem;
}

.tbl-wrap {
  border: 1px solid var(--bdr);
  border-radius: var(--r);
  overflow: hidden;
  max-height: 560px;
  overflow-y: auto;
  box-shadow: 0 1px 3px rgba(0,0,0,.07);
}

table { width: 100%; border-collapse: collapse; }

thead {
  background: #f1f4fb;
  position: sticky;
  top: 0;
  z-index: 2;
}
th {
  padding: .625rem .75rem;
  font: 600 .75rem var(--f);
  text-transform: uppercase;
  letter-spacing: .06em;
  color: var(--mut);
  text-align: left;
  border-bottom: 1px solid var(--bdr);
}
td {
  padding: .25rem .375rem;
  border-bottom: 1px solid #edf0f7;
  vertical-align: middle;
}
tbody tr:last-child td   { border-bottom: none; }
tbody tr:nth-child(even) { background: var(--alt); }
tbody tr.hi {
  background: var(--hl) !important;
  box-shadow: inset 3px 0 0 var(--hlb);
}

.th-n, .n {
  width: 3rem;
  text-align: right;
  color: var(--mut);
  font-size: .75rem;
  padding-right: .75rem;
  user-select: none;
}
.th-rfid { width: 9rem; }

td input[type=text] {
  width: 100%;
  max-width: none;
  padding: .3rem .45rem;
  border: 1px solid transparent;
  border-radius: 3px;
  background: transparent;
  font: .875rem var(--f);
  transition: border-color .1s, background .1s;
  outline: none;
}
td input.rfid { font-family: var(--fm); font-size: .8125rem; }
td input:focus {
  border-color: var(--pri);
  background: #fff;
  box-shadow: 0 0 0 2px rgba(74,108,247,.12);
}

#toast {
  position: fixed;
  bottom: 1.5rem;
  right: 1.5rem;
  background: #1e2535;
  color: #e8edf8;
  font-size: .875rem;
  padding: .625rem 1rem;
  border-radius: 4px;
  box-shadow: 0 2px 8px rgba(0,0,0,.15);
  opacity: 0;
  transform: translateY(6px);
  transition: opacity .2s, transform .2s;
  pointer-events: none;
  z-index: 100;
}
#toast.on  { opacity: 1; transform: translateY(0); }
#toast.err { background: #c0392b; }
)TOKIWEB";

static const char WEB_JS[] = R"TOKIWEB(// Tab switching
const tabs   = document.querySelectorAll('.tab');
const panels = document.querySelectorAll('.panel');

tabs.forEach(t => t.addEventListener('click', () => {
  tabs.forEach(b => b.classList.remove('active'));
  panels.forEach(p => p.classList.remove('active'));
  t.classList.add('active');
  const panel = document.getElementById('tab-' + t.dataset.tab);
  panel.classList.add('active');
  if (t.dataset.tab === 'map') {
    document.querySelector('#map-body tr.hi')
      ?.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
  }
}));

// API helpers
const get  = path => fetch(path).then(r => { if (!r.ok) throw r.status; return r.json(); });
const post = (path, data) => fetch(path, {
  method: 'POST',
  headers: { 'Content-Type': 'application/json' },
  body: JSON.stringify(data),
}).then(r => { if (!r.ok) throw r.status; return r.json(); });

// Toast
let _tt;
const toast = (msg, ok = true) => {
  const el = document.getElementById('toast');
  el.textContent = msg;
  el.className = 'on' + (ok ? '' : ' err');
  clearTimeout(_tt);
  _tt = setTimeout(() => el.classList.remove('on'), 3000);
};

// Credentials
get('/api/credentials').then(d => {
  const f = document.getElementById('form-creds');
  for (const [k, v] of Object.entries(d)) if (f.elements[k]) f.elements[k].value = v;
}).catch(e => console.warn('credentials load failed', e));

document.getElementById('form-creds').addEventListener('submit', async e => {
  e.preventDefault();
  const f = e.target;
  try {
    await post('/api/credentials', {
      wifi_ssid:      f.elements.wifi_ssid.value.trim(),
      wifi_password:  f.elements.wifi_password.value,
      admin_username: f.elements.admin_username.value.trim(),
      admin_password: f.elements.admin_password.value,
    });
    toast('Credentials saved.');
  } catch { toast('Save failed.', false); }
});

document.getElementById('btn-restart').addEventListener('click', async () => {
  if (!confirm('Restart the device now?')) return;
  try {
    await fetch('/api/restart', { method: 'POST' });
    toast('Device is restarting\u2026');
  } catch { toast('Restart failed.', false); }
});

// Server config
get('/api/server-config').then(d => {
  const f = document.getElementById('form-srv');
  for (const [k, v] of Object.entries(d)) if (f.elements[k]) f.elements[k].value = v;
}).catch(e => console.warn('server-config load failed', e));

document.getElementById('form-srv').addEventListener('submit', async e => {
  e.preventDefault();
  const f = e.target;
  try {
    await post('/api/server-config', {
      server_host: f.elements.server_host.value.trim(),
      server_port: parseInt(f.elements.server_port.value, 10),
    });
    toast('Server config saved.');
  } catch { toast('Save failed.', false); }
});

// Music mapping
let entries = [];

get('/api/music-mapping').then(d => {
  const raw = d.entries ?? [];
  entries = Array.from({ length: 100 }, (_, i) => raw[i] ?? { rfid: '', label: '' });
  renderMap();
}).catch(e => console.warn('mapping load failed', e));

const esc = s => String(s)
  .replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');

function renderMap() {
  const frag = document.createDocumentFragment();
  entries.forEach((e, i) => {
    const tr = document.createElement('tr');
    tr.dataset.i = i;
    tr.innerHTML =
      `<td class="n">${i + 1}</td>` +
      `<td><input type="text" class="rfid" value="${esc(e.rfid)}" placeholder="RFID" spellcheck="false"></td>` +
      `<td><input type="text" value="${esc(e.label)}" placeholder="path or URL"></td>`;
    frag.appendChild(tr);
  });
  const body = document.getElementById('map-body');
  body.innerHTML = '';
  body.appendChild(frag);
}

function collect() {
  document.querySelectorAll('#map-body tr').forEach((tr, i) => {
    const [rfidIn, labelIn] = tr.querySelectorAll('input');
    entries[i] = { rfid: rfidIn.value.trim(), label: labelIn.value.trim() };
  });
}

document.getElementById('btn-save-map').addEventListener('click', async () => {
  collect();
  try {
    await post('/api/music-mapping', { entries });
    toast('Mapping saved.');
  } catch { toast('Save failed.', false); }
});

// RFID highlight / auto-fill
let lastUid = '';

function highlight(i) {
  document.querySelectorAll('#map-body tr').forEach(r => r.classList.remove('hi'));
  const tr = document.querySelector(`#map-body tr[data-i="${i}"]`);
  if (!tr) return;
  tr.classList.add('hi');
  if (document.getElementById('tab-map').classList.contains('active'))
    tr.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
}

function onScan(uid) {
  collect();
  const i = entries.findIndex(e => e.rfid.toUpperCase() === uid.toUpperCase());
  if (i >= 0) { highlight(i); return; }
  const empty = entries.findIndex(e => !e.rfid.trim());
  if (empty >= 0) { entries[empty].rfid = uid; renderMap(); highlight(empty); }
}

// Poll last scanned RFID every 2 s
setInterval(() =>
  get('/api/last-rfid').then(d => {
    if (d.uid && d.uid !== lastUid) { lastUid = d.uid; onScan(d.uid); }
  }).catch(() => {}),
2000);
)TOKIWEB";
